"use client";
import { useCallback, useEffect, useState } from 'react';
import { BookOpen, CheckCircle2, FileSearch, ImageUp, KeyRound, Send, Sparkles } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Skeleton } from '@/components/ui/skeleton';
import type { GrammarResult, ResumeResult } from '@/lib/ai-contract';
import { clarificationFor } from '@/lib/grammar-safety';
import { normalizeApiKey } from '@/lib/api-key';

type View='grammar'|'resume'|'courses'|'gd';
type Course={name:string;level:string;duration:string;reason:string};
type Metric={score:number;feedback:string};
type Discussion={grammar:Metric;clarity:Metric;content:Metric;confidenceFeedback:string;improvements:string[]};
type Results={connect:{connected:boolean;model:string};grammar:GrammarResult;ocr:{text:string;notes:string};resume:ResumeResult;courses:{courses:Course[]};topic:{topic:string};gd:Discussion};
const sample='I has compleated my machine learning project and want improve my resume.';
export default function AIWorkspace({view,remember}:{view:View;remember:(message:string)=>void}){
  const [key,setKey]=useState('');const [draftKey,setDraftKey]=useState('');const [connected,setConnected]=useState(false);const [model,setModel]=useState('');
  const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const [writing,setWriting]=useState(sample);const [grammar,setGrammar]=useState<GrammarResult|null>(null);const [checkedText,setCheckedText]=useState('');const [scanNote,setScanNote]=useState('');
  const [file,setFile]=useState<File|null>(null);const [resume,setResume]=useState<ResumeResult|null>(null);
  const [goal,setGoal]=useState('Machine Learning Engineer');const [skills,setSkills]=useState('');const [courses,setCourses]=useState<Course[]>([]);
  const [topic,setTopic]=useState('Should AI replace repetitive jobs?');const [answer,setAnswer]=useState('');const [gd,setGd]=useState<Discussion|null>(null);

  const request=useCallback(async<A extends keyof Results,>(action:A,fields:Record<string,string|File>={},apiKey=key):Promise<Results[A]>=>{
    const form=new FormData();form.set('action',action);Object.entries(fields).forEach(([name,value])=>form.set(name,value));
    const response=await fetch('/api/assist',{method:'POST',headers:apiKey?{'x-careermate-key':apiKey}:{},body:form,signal:AbortSignal.timeout(100000)});
    const data=await response.json();if(!response.ok)throw new Error((data as {error?:string}).error||'Request failed. Please retry.');return data as Results[A];
  },[key]);
  const run=async(action:string,work:()=>Promise<void>)=>{if(busy)return;setBusy(action);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Unable to connect. Try again.');}finally{setBusy('');}};
  const check=useCallback(async(value:string)=>{
    if(!value.trim()||value.length>8000)throw new Error('Enter 1 to 8,000 characters.');
    const data:GrammarResult=clarificationFor(value)||await request('grammar',{text:value});setGrammar(data);setCheckedText(value);remember((data.clarification?'Clarification · ':'Grammar · ')+data.corrected);return data;
  },[request,remember]);

  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
    if(!context)return;const lifecycle=new AbortController();
    try{Promise.resolve(context.registerTool({name:'check_writing',description:'Check spelling and grammar with Gemini and update the visible result.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:8000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const value=(input as {text?:unknown})?.text;if(typeof value!=='string')throw new Error('text must be a string');setWriting(value);return await check(value);}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Unsupported registration leaves UI usable. */}
    return()=>lifecycle.abort();
  },[check]);

  return <>
    <section className="card mb-5" aria-label="Gemini connection">
      <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-semibold"><KeyRound size={18}/> {connected?'Gemini connected':'Connect Gemini'}</h2>{connected&&<button className="secondary" disabled={!!busy} onClick={()=>{setKey('');setDraftKey('');setConnected(false);setModel('');}}>Disconnect</button>}</div>
      {!connected?<form className="mt-3 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void run('connect',async()=>{const cleanKey=normalizeApiKey(draftKey);const data=await request('connect',{},cleanKey);setKey(cleanKey);setDraftKey('');setConnected(true);setModel(data.model);});}}>
        <input aria-label="Gemini API key" type="password" autoComplete="off" spellCheck={false} maxLength={2048} value={draftKey} disabled={!!busy} onChange={e=>{setDraftKey(e.target.value);setError('');}} placeholder="Paste the full key using Google AI Studio’s Copy button" className="input min-w-48"/>
        <button className="primary" disabled={!!busy}>{busy==='connect'?'Checking…':'Connect Gemini'}</button>
      </form>:<p className="mt-2 text-sm text-emerald-800">Key accepted · {model}. Generation remains subject to your Google quota.</p>}
      <p className="mt-3 text-sm text-slate-500">Your key stays in this page’s memory and is sent securely to the backend and Google. Refreshing clears it. Text and uploads are sent to Gemini for analysis; this app does not save files. { !connected&&'Leave blank to use a server-configured key, if available.'}</p>
    </section>
    {error&&<div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
    {view==='grammar'&&<div className="grid gap-5 lg:grid-cols-2"><section className="card"><Title title="Write with confidence" sub="Correct spelling and grammar without changing your meaning."/>
      <textarea aria-label="Text to check" className="textarea" value={writing} disabled={!!busy} maxLength={8000} onChange={e=>{setWriting(e.target.value);setGrammar(null);}}/>
      <div className="mt-3 flex flex-wrap gap-3"><button className="secondary" disabled={!!busy} onClick={()=>{setWriting(sample);setGrammar(null);}}>Use example</button><label className="secondary"><ImageUp size={17}/> Scan Text from Image<input aria-label="Image to transcribe" type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" disabled={!!busy} onChange={e=>{const image=e.target.files?.[0];if(image)void run('ocr',async()=>{if(image.size>5*1024*1024)throw new Error('Maximum file size is 5 MB.');const data=await request('ocr',{file:image});setWriting(data.text);setScanNote(data.notes||(!data.text?'No readable text found.':''));setGrammar(null);remember('Image transcription completed');});e.target.value='';}}/></label><button className="primary" disabled={!!busy||!writing.trim()} onClick={()=>void run('grammar',async()=>{await check(writing);})}><Sparkles size={17}/> Check writing</button></div>
      {scanNote&&<p className="mt-3 text-sm text-slate-600">{scanNote}</p>}
    </section><section className="card"><Title title="AI suggestions" sub="Corrections are based on your submitted text."/>{busy?<Loading/>:grammar?<div className="mt-4 space-y-4"><div className="rounded-xl bg-emerald-50 p-4"><b>{grammar.clarification ? "Clarification needed — original kept" : "Suggested correction"}</b><p className="mt-2 whitespace-pre-wrap leading-7">{grammar.corrected}</p></div><p className="text-sm">{grammar.explanation}</p>{grammar.clarification&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-medium">{grammar.clarification}</p>{/\bwont\b/i.test(writing)&&<div className="mt-3 flex flex-wrap gap-2">{["want","won’t"].map(word=><button className="secondary" disabled={!!busy} key={word} onClick={()=>{const value=writing.replace(/\bwont\b/gi,word);setWriting(value);setGrammar(null);void run('grammar',async()=>{await check(value);});}}>I mean “{word}”</button>)}</div>}</div>}<div><b>Original with mistakes highlighted</b><p className="mt-2 whitespace-pre-wrap leading-7"><Highlighted text={checkedText} changes={grammar.changes}/></p></div>{grammar.changes.map((c,i)=><div className="rounded-xl border p-3 text-sm" key={i}><p><mark>{c.original||'(insertion)'}</mark> → <strong>{c.replacement}</strong></p><p className="mt-1 text-slate-600">{c.explanation}</p></div>)}</div>:<Empty text="Check your text to see corrections."/>}</section></div>}
    {view==='resume'&&<div className="grid gap-5 lg:grid-cols-2"><section className="card"><Title title="Upload your resume" sub="PDF or DOCX, maximum 5 MB. Image-only PDFs are supported through Gemini."/>
      <label className="mt-4 block text-sm font-semibold">Target role (optional)<input className="input mt-2 block w-full" value={goal} maxLength={200} disabled={!!busy} onChange={e=>setGoal(e.target.value)}/></label>
      <label className="mt-5 block rounded-xl border-2 border-dashed border-blue-200 p-6"><span className="block font-medium">Choose your resume</span><input className="mt-3 block max-w-full text-sm" type="file" accept=".pdf,.docx" disabled={!!busy} onChange={e=>{setFile(e.target.files?.[0]||null);setResume(null);}}/></label>
      <button className="primary mt-4" disabled={!!busy||!file} onClick={()=>void run('resume',async()=>{if(!file)return;if(file.size>5*1024*1024)throw new Error('Maximum file size is 5 MB.');const data=await request('resume',{file,goal});setResume(data);setSkills(data.skills.join(', '));remember('Resume analyzed · '+file.name);})}><FileSearch size={17}/> Analyze resume</button>
    </section><section className="card"><Title title="Resume analysis" sub="Evidence-based completeness estimate, not a commercial ATS score or hiring prediction."/>{busy?<Loading/>:resume?<div className="mt-4 space-y-4"><div className="rounded-xl bg-[#0a2149] p-4 text-white"><strong className="text-3xl">{resume.score}/100</strong><p>Resume readiness estimate</p></div><List title="Skills found" values={resume.skills}/><List title="Education" values={resume.education}/><List title="Projects" values={resume.projects}/><List title="Suggested skill gaps for target role" values={resume.missingSkills}/><List title="Improvements" values={resume.improvements}/><details><summary className="cursor-pointer font-semibold">Scoring evidence</summary>{resume.rubric.map(row=><p className="my-2 text-sm" key={row.criterion}><b>{row.criterion}: {row.points}/{row.maximum}</b><br/>{row.evidence||'No supporting text found.'}</p>)}</details><details><summary className="cursor-pointer font-semibold">Extracted text — review for errors</summary><p className="mt-2 whitespace-pre-wrap text-sm">{resume.extractedText}</p></details></div>:<Empty text="Upload a resume to see its actual contents and feedback."/>}</section></div>}
    {view==='courses'&&<section className="card"><Title title="Your learning path" sub="Three AI-suggested course topics. Durations are estimates; provider listings are not verified."/><label className="mt-4 block font-medium">Career goal<input className="input mt-2 block w-full" value={goal} maxLength={200} disabled={!!busy} onChange={e=>setGoal(e.target.value)}/></label><label className="mt-4 block font-medium">Current skills<textarea className="textarea min-h-24" maxLength={4000} value={skills} disabled={!!busy} onChange={e=>setSkills(e.target.value)} placeholder="Enter your skills, or analyze your resume first."/></label><p className="my-3 text-sm text-slate-500">{resume?'Your analyzed resume will also inform these recommendations.':'Add skills for more personal recommendations.'}</p><button className="primary" disabled={!!busy||!goal.trim()} onClick={()=>void run('courses',async()=>{const data=await request('courses',{goal,profile:JSON.stringify({skills,resume:resume?{skills:resume.skills,education:resume.education,projects:resume.projects}:null}).slice(0,20000)});setCourses(data.courses);remember('Learning path · '+goal);})}><BookOpen size={17}/> Build my path</button>{busy?<Loading/>:<div className="mt-5 grid gap-4 lg:grid-cols-3">{courses.map((c,i)=><article key={i} className="rounded-xl border p-5"><p className="text-sm text-blue-700">{c.level} · {c.duration}</p><h3 className="my-3 text-lg font-bold">{c.name}</h3><p className="text-sm leading-6">{c.reason}</p></article>)}</div>}</section>}
    {view==='gd'&&<div className="grid gap-5 lg:grid-cols-2"><section className="card"><Title title="Group discussion practice" sub="Practise an opening, supporting points and a conclusion."/><div className="mt-4 rounded-xl bg-[#0a2149] p-4 text-white"><p>{topic}</p></div><button className="secondary mt-3" disabled={!!busy} onClick={()=>void run('topic',async()=>{const data=await request('topic',{topic});setTopic(data.topic);setAnswer('');setGd(null);remember('GD topic · '+data.topic);})}>Generate new topic</button><textarea aria-label="GD response" className="textarea" maxLength={8000} value={answer} disabled={!!busy} onChange={e=>{setAnswer(e.target.value);setGd(null);}} placeholder="Write your response (at least 20 characters)."/><button className="primary mt-3" disabled={!!busy||answer.trim().length<20} onClick={()=>void run('gd',async()=>{const data=await request('gd',{topic,text:answer});setGd(data);remember('GD feedback · '+topic);})}><Send size={17}/> Get feedback</button></section><section className="card"><Title title="Written discussion feedback" sub="AI feedback on your answer. Spoken confidence cannot be measured from text."/>{busy?<Loading/>:gd?<div className="mt-4 space-y-5">{(['grammar','clarity','content'] as const).map(name=><div key={name}><p className="mb-2 capitalize font-semibold">{name}: {gd[name].score}/100</p><Progress value={gd[name].score}/><p className="mt-2 text-sm">{gd[name].feedback}</p></div>)}<p className="rounded-xl bg-blue-50 p-4 text-sm">{gd.confidenceFeedback}</p><List title="Next improvements" values={gd.improvements}/></div>:<Empty text="Submit your answer for specific feedback."/>}</section></div>}
  </>;
}
function Title({title,sub}:{title:string;sub:string}){return <div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{sub}</p></div>;}
function Empty({text}:{text:string}){return <p className="py-12 text-center text-slate-500">{text}</p>;}
function Loading(){return <div role="status" className="space-y-3 py-8"><p className="text-sm text-slate-500">Gemini is processing…</p><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-4/5"/></div>;}
function List({title,values}:{title:string;values:string[]}){return <div><h3 className="font-semibold">{title}</h3>{values.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{values.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="mt-1 text-sm text-slate-500">None identified.</p>}</div>;}
function Highlighted({text,changes}:{text:string;changes:GrammarResult['changes']}){
  const ranges=changes.flatMap(c=>{const start=c.original?text.indexOf(c.original):-1;return start<0?[]:[{start,end:start+c.original.length}];}).sort((a,b)=>a.start-b.start);
  const nodes:React.ReactNode[]=[];let end=0;for(const range of ranges){if(range.start<end)continue;nodes.push(text.slice(end,range.start));nodes.push(<mark key={range.start} className="bg-amber-100 text-amber-950">{text.slice(range.start,range.end)}</mark>);end=range.end;}nodes.push(text.slice(end));return <>{nodes}</>;
}
